### ISSUE TITLE
記事詳細画面の検討と実装

### ISSUE THREAD

**Issue by ryusukevlc** [ryusukevlc/Morgenrot#5]
一般向けのhome画面から記事を選択した際に遷移する記事詳細画面を作成する。

以下内容について検討・実装する。
***

#### フロント側
- 記事詳細画面に表示する内容（タイトル、コンテンツ、作成日付、更新日付、タグ等）
- 記事詳細画面のデザイン（タイトル、コンテンツ等の配置）
- 上記決定事項の実装

#### サーバー側
- 記事詳細画面への遷移処理の実装

**Comment by ryusuke14520** [comment]
記事詳細画面への遷移処理と、記事詳細画面の仮実装は終えた

**Comment by ryusuke14520** [comment]
残タスク：

- 記事詳細画面に遷移する前にバリデーションをかける
- 記事詳細画面のデザインの実装
- 記事詳細画面に、作成日付と更新日付も渡す
-
